# for SBT <-> Travis integration best practices see
# http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html

# Use container-based infrastructure
sudo: false

language:
  - scala

scala:
  - 2.11.8

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

# avoid unnecessary cache updates
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

script:
  - sbt clean coverage "test-only -- -l NotOnTravis" coverageReport -Dswave.test.timing.factor=1.05 &&
    sbt coverageAggregate

after_success:
  - sbt coveralls